### ISSUE TITLE
Why the fuck is the browser 2 gigabytes

### ISSUE THREAD

**Issue by stysan** [face-hh/wattesigma#1]

**Comment by bazelik-null** [comment]
still better than chrome

**Comment by alternativebyte** [comment]
bloated chrome

**Comment by Lecrapouille** [comment]
It's 2 GB because of shared lib CEF is 1.3 GB on Linux. For Windows it's lighter since, because contrary to Linux not all symbols are exported.

**Comment by RealPacket-sys** [comment]
It's because someone forgot to remove the cache from the build...
