### ISSUE TITLE
Port it to arch Linux AUR. I dare you

### ISSUE THREAD

**Issue by Minecradt** [face-hh/wattesigma#14]

**Comment by Lecrapouille** [comment]
What about adding cef_artifacts released 0.12.1 from GitHub on the root folder of the project ? Not working ?

**Comment by rabaimorp** [comment]
there is no need for a specific arch package from the dev. as long as there a linux build you can write your own pkgbuild in a few minutes

**Comment by Unknown303YT** [comment]
there is no linux build but i am making one. itll prob be done in 2 years lmao
