### ISSUE TITLE
how do i compile

### ISSUE THREAD

**Issue by rooootdev** [face-hh/wattesigma#16]
yea kinda self explanitory. i put cef in root and shit but GDCef Node type is not availible

**Comment by mrhoomanwastaken** [comment]
https://docs.godotengine.org/en/stable/contributing/development/compiling/index.html

**Comment by mrhoomanwastaken** [comment]
or if its not in there ask chat gpt it will know.

**Comment by mrhoomanwastaken** [comment]
found it


Configure CEF:

    Download the cef_artifacts file off the Releases from the gdcef repository.
    Extract the contents to the project root. You should have the folders cef_artifacts, Website, Assets, Shaders, ...

Run the project from the Godot editor or export it for your target platform.

**Comment by rooootdev** [comment]
thanks!
