### ISSUE TITLE
is the 2 gb supposed to be a bypass to aniviruses or

### ISSUE THREAD

**Issue by alternativebyte** [face-hh/wattesigma#2]
is it just like that

**Comment by Badbird5907** [comment]
yes'nt

**Comment by face-hh** [comment]
No, it's the actual file size. I will try to decrease it in the next release.

**Comment by face-hh** [comment]
Duplicate of #1

**Comment by Unknown303YT** [comment]
why open and close, @face-hh

**Comment by face-hh** [comment]
> why open and close, @face-hh 

I closed it as "not planned" by mistake, which was not accurate. I closed it again as "completed", because it's a duplicate and will be fixed in the next release
