### ISSUE TITLE
Linux and Macos Versions are not available

### ISSUE THREAD

**Issue by turtle-key** [face-hh/wattesigma#28]
You made your own browser, used chromium and implemented it just for windows. Come on! At least the linux app should be available. What's with your hate with linux. Windows is the worst, it collects all your data. :(

**Comment by supervitu64** [comment]
have you heard of wine-stable

**Comment by mrhoomanwastaken** [comment]
> have you heard of wine-stable

wine is not real I made it up.

**Comment by turtle-key** [comment]
Thanks!


On Saturday, October 19, 2024, 05:51, mrhoomanwastaken ***@***.***> wrote:





have you heard of wine-stable


wine is not real I made it up.

**Comment by Lecrapouille** [comment]
@turtle-key a freshly pull request made gdCEF normally working for MacOS. This is in alpha. I do not have a Mac so I could not test directly, no yet CI to make prebuilt artifacts

**Comment by Lecrapouille** [comment]
@turtle-key you can give a try on https://github.com/Lecrapouille/gdcef/releases/tag/v0.13.0-godot4 with MacOS

**Comment by mrhoomanwastaken** [comment]
on my arch (btw) installation a simple win 10 wine installation does the trick. I would not be surprised if it would work on mac as well. also compiling for different apps is not as simple as just telling godot to compile for them.

**Comment by mrhoomanwastaken** [comment]
but because its mostly shaders you might be able to compile it with little trouble.

**Comment by Lecrapouille** [comment]
@mrhoomanwastaken gdcef is not, as simple to compile and run as you said, but once done, the gd script part is the same whatever the operating system.
