### ISSUE TITLE
get_title()

### ISSUE THREAD

**Issue by Lecrapouille** [face-hh/wattesigma#5]
Dude, you did not made the PR concerning the get_title() I have to add it on my API for the next version 0.12.1

**Comment by Lecrapouille** [comment]
For my defense https://youtu.be/37ISfJ2NSXQ?feature=shared&t=74 I was waiting for the PR :) I'm releasing on https://github.com/Lecrapouille/gdcef/releases/tag/v0.12.1-godot4 (the CI is currently processing for Windows).

**Comment by face-hh** [comment]
My bad, I had to rush the video release a little lol

I'll update the docs accordingly when I get home
