### ISSUE TITLE
Cannot get release or custom build to launch the cef browser.

### ISSUE THREAD

**Issue by SmilerRyan** [face-hh/wattesigma#7]
After extracting the release and checking the console logs (i copied the godot console.exe to the release as ``BussinWattesigma_console.exe`` and run it) i get this error.

```
ERROR: Can't open dynamic library: cef_artifacts/libgdcef.dll. Error: Error 126: The specified module could not be found..
   at: (platform/windows/os_windows.cpp:455)
ERROR: Can't open GDExtension dynamic library: cef_artifacts/libgdcef.dll
   at: (core/extension/gdextension.cpp:802)
ERROR: Failed loading resource: res://cef_artifacts/gdcef.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:283)
ERROR: Error loading extension: res://cef_artifacts/gdcef.gdextension
   at: (core/extension/gdextension_manager.cpp:234)
Godot Engine v4.3.stable.official.77dcf97d8 - https://godotengine.org
Vulkan 1.3.215 - Forward+ - Using Device #0: Intel - Intel(R) UHD Graphics 630

ERROR: Cannot get class 'GDCef'.
   at: (core/object/class_db.cpp:515)
WARNING: Node CEF of type GDCef cannot be created. A placeholder will be created instead.
     at: instantiate (scene/resources/packed_scene.cpp:277)
ERROR: Node not found: "Panel/VBox/HBox2/Info" (relative to "/root/GUI").
   at: (scene/main/node.cpp:1792)
ERROR: <null>
   at: push_error (core/variant/variant_utility.cpp:1092)
```

As far as I can tell the file does exist, so I'm not sure what to try next.

![image](https://github.com/user-attachments/assets/91813f67-846f-4135-8502-a4b3238d64fa)

**Comment by Lecrapouille** [comment]
@SmilerRyan Hi

- you need the 0.12.1 for fixing the missing get_title() function. The CI is processing so Windows is coming in a few minutes. https://github.com/Lecrapouille/gdcef/releases/tag/v0.12.1-godot4

- cef_artifacts shall be in the root folder of the project. See:

![Capture d’écran_2024-09-24_00-31-31](https://github.com/user-attachments/assets/ab4a0a7c-2d9f-40a0-80c7-f836f58f67a6)

- There is a possible bug on Windows that I cannot catch where the dll is not found.

**Comment by SmilerRyan** [comment]
Sounds good. With the cef_artifacts from this release, the project files and the godot 4.3 editor, this does work now.
In my case I was also missing ``vcomp140.dll`` (i like to install as little as possible) but that's the only change I had to make.
![image](https://github.com/user-attachments/assets/7620733e-9823-40cf-a4d3-38099a61c32e)
