### ISSUE TITLE
Wattesigma on Linux

### ISSUE THREAD

**Issue by ItzDerock** [face-hh/wattesigma#8]
for the Linux users out there, I was able to run the Windows build using bottles after changing the runner to `kron4ek-wine-9.11-stable`. My system's wine-8.2 did not work (app crashed on launch), and the bottles default of soda-9.0 didnt work either (CEF failed to load). If you try to run this without bottles, make sure you use a 64-bit Wine build.

**Comment by Lecrapouille** [comment]
Yes, you're right the GitHub CI runs on 64-bits archi. Not sure how to set the CI to compile for 32-bits (Linux/Windows) and if this makes sense nowadays to keep maintaining 32-bits.

**Comment by face-hh** [comment]
Linux support will not be added to the Releases tab, although you'll be able to compile the `cef_artifcts` for Linux hopefully soon, which will allow you to use the browser normally if you export it as an executable file through Godot.
